apiVersion: apps/v1
kind: Deployment
metadata:
  name: org1peer0
spec :
  replicas : 1
  template :
    metadata:
      labels:
        name: org1peer0
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
    - name : peer
      image: hyperledger/fabric-peer:1.4.4
      command : ["sh,"-c","peer node start"]
      env:
      - name: TZ
        value: "Asia"
      - name: CORE_PEER_ADDRESSAUTODETECT
        value: "true"
      - name: CORE_PEER_ID
        value: peer0.org1.dairy.com
      # - name: CORE_PEER_NETWORKID
      #   value: nid1
      - name: CORE_PEER_ADDRESS
        value: peer0.org1.dairy.com:7051
      - name: CORE_PEER_LISTENADDRESS
        value: 0.0.0.0:7051
      - name: CORE_PEER_EVENTS_ADDRESS
        value: 0.0.0.0:7061
      - name: CORE_PEER_CHAINCODELISTENADDRESS
        value: 0.0.0.0:7052
      - name: CORE_PEER_GOSSIP_BOOTSTRAP
        value: peer0.org1.dairy.com:7051
      - name: CORE_PEER_GOSSIP_ENDPOINT
        value: peer0.org1.dairy.com:7051
      - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
        value: peer0.org1.dairy.com:7051
      - name: CORE_PEER_GOSSIP_ORGLEADER
        value: "true"
      - name: CORE_PEER_GOSSIP_USELEADERELECTION
        value: "true"
      - name: CORE_PEER_PROFILE_ENABLED
        value: "true"
      - name: CORE_VM_ENDPOINT
        value: unix:///host/var/run/docker.sock
      - name: CORE_PEER_LOCALMSPID
        value: Org1MSP
      - name: CORE_PEER_MSPCONFIGPATH
        value: /fabric/crypto-config/peerOrganizations/org1.dairy.com/peers/peer0.org1.dairy.com/msp/
      - name: FABRIC_LOGGING_SPEC
        value: "debug"
      - name: CORE_PEER_TLS_ENABLED
        value: "true"
      - name: CORE_PEER_TLS_CERT_FILE
        value: /fabric/crypto-config/peerOrganizations/org1.dairy.com/peers/peer0.org1.dairy.com/tls/server.crt
      - name: CORE_PEER_TLS_KEY_FILE
        value: /fabric/crypto-config/peerOrganizations/org1.dairy.com/peers/peer0.org1.dairy.com/tls/server.key
      - name: CORE_PEER_TLS_ROOTCERT_FILE
        value: /fabric/crypto-config/peerOrganizations/org1.dairy.com/peers/peer0.org1.dairy.com/tls/ca.crt
      - name: CORE_LEDGER_STATE_STATEDATABASE
        value: "CouchDB"
      - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
        value: "localhost:5984"
      - name: FABRIC_CFG_PATH
        value: /etc/hyperledger/fabric/
      - name: ORDERER_URL
        value: orderer:7050
      - name: ORDERER_URL
        value: orderer2:7050
      - name: ORDERER_URL
        value: orderer3:7050
      - name: ORDERER_URL
        value: orderer4:7050
      - name: ORDERER_URL
        value: orderer5:7050
      volumeMounts:
      - mountPath: /fabric
        name: fabricfiles
      - mountPath: /host/var/run/docker.sock
        name: dockersocket
    - name: couchdb
      image: hyperledger/fabric-couchdb:0.4.15
          # - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
        #   value: "hyperledgeruser"
        # - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
        #   value: "hyperledgerpass"
