# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: efs-burst-persistent-volume
# spec:
#   storageClassName: nfs
#   capacity:
#     storage: 100Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   mountOptions:
#     - hard
#     - nfsvers=4.1
#     - rsize=1048576
#     - wsize=1048576
#     - timeo=600
#     - retrans=2
#   nfs:
#     path: /
#     server: fs-b30177aa.efs.us-west-1.amazonaws.com

apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pv
  labels:
    type: local
    name: fabricfiles
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs
    path: "/nfs/fabric"
    readOnly: false

