# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: efs-burst-persistent-volume-claim
# spec:
#   storageClassName: nfs
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-pvc
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: fabricfiles